const { contextBridge, ipcRenderer } = require('electron');

// Expose safe APIs to the renderer process
contextBridge.exposeInMainWorld('electronAPI', {
  sendMessage: (message) => ipcRenderer.send('message-from-renderer', message),
  onMessage: (callback) => ipcRenderer.on('message-from-main', (event, data) => callback(data)),
  onNavigate: (callback) => ipcRenderer.on('navigate-to', callback),
  onChangePassword: (callback) => ipcRenderer.on('change-password-modal', callback),
  showMenu: () => ipcRenderer.send('show-menu'),
  hideMenu: () => ipcRenderer.send('hide-menu'),
  saveCanvasFile: (dataUrl, filename) => ipcRenderer.invoke('save-canvas-file', { dataUrl, filename }),
  clearCanvasPreviews: () => ipcRenderer.invoke('clear-canvas-previews'),
  onShowAlert: (callback) => ipcRenderer.on('show-alert', (event, data) => callback(data)),
  setRolePermissionsData: (data) => ipcRenderer.send('role-permissions-data', data),
  // Updater APIs
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  cancelDownloadUpdate: () => ipcRenderer.invoke('cancel-download-update'),
  onUpdateEvent: (callback) => ipcRenderer.on('update-event', (_event, data) => callback(data)),
  onReportSOTanggal: (callback) => ipcRenderer.on('open-report-so-tanggal', callback),
  onReportRealisasiWOTanggal: (callback) => ipcRenderer.on('open-report-wo-actual-tanggal', callback),
  onReportInvoicePenjualanTanggal: (callback) => ipcRenderer.on('open-report-invoice-tanggal', callback),
  onReportPenjualanGudangTanggal: (callback) => ipcRenderer.on('open-report-penjualan-gudang-tanggal', callback),
  onReportPenjualanGudangBarang: (callback) => ipcRenderer.on('open-report-penjualan-gudang-barang', callback),
  onReportPenjualanBarangGlobal: (callback) => ipcRenderer.on('open-report-penjualan-barang-global', callback),
  onReportPenjualanPelangganBarang: (callback) => ipcRenderer.on('open-report-penjualan-pelanggan-barang', callback),
  onReportPenjualanPelangganTanggal: (callback) => ipcRenderer.on('open-report-penjualan-pelanggan-tanggal', callback),
  onReportInvoicePiutangPelanggan: (callback) => ipcRenderer.on('open-report-invoice-piutang-pelanggan', callback),
  onReportPembayaranUMPiutang: (callback) => ipcRenderer.on('open-report-pembayaran-um-piutang', callback),
  onReportFakturPembelianTanggal: (callback) => ipcRenderer.on('open-report-faktur-pembelian-tanggal', callback),
  onReportPembelianGudangTanggal: (callback) => ipcRenderer.on('open-report-pembelian-gudang-tanggal', callback),
  onReportPembelianGudangBarang: (callback) => ipcRenderer.on('open-report-pembelian-gudang-barang', callback),
  onReportPembelianBarangGlobal: (callback) => ipcRenderer.on('open-report-pembelian-barang-global', callback),
  onReportInvoiceHutangSupplier: (callback) => ipcRenderer.on('open-report-invoice-hutang-supplier', callback),
  onReportPemakaianKasJenisBiaya: (callback) => ipcRenderer.on('open-report-pemakaian-kas-jenis-biaya', callback),
  onReportStockGudangBarang: (callback) => ipcRenderer.on('open-report-stock-gudang-barang', callback),
  onReportStockBarangGudang: (callback) => ipcRenderer.on('open-report-stock-barang-gudang', callback),
  onReportStockGlobal: (callback) => ipcRenderer.on('open-report-stock-global', callback),
  onReportTrackingSOWO: (callback) => ipcRenderer.on('open-report-tracking-so-wo', callback),
  onReportMutasiAntarGudang: (callback) => ipcRenderer.on('open-report-mutasi-antar-gudang', callback),
  onReportRubahStatusBarang: (callback) => ipcRenderer.on('open-report-rubah-status-barang', callback),
  onReportStockOpname: (callback) => ipcRenderer.on('open-report-stock-opname', callback),
  onReportKegiatanPelaksana: (callback) => ipcRenderer.on('open-report-kegiatan-pelaksana', callback),
  onReportRekapKegiatanPelaksana: (callback) => ipcRenderer.on('open-report-rekap-kegiatan-pelaksana', callback),
  onReportRincianKeuangan: (callback) => ipcRenderer.on('open-report-rincian-keuangan', callback),
  onReportRekapLabaOperasional: (callback) => ipcRenderer.on('open-report-rekap-laba-operasional', callback),
  onRequestConfirm: (callback) => ipcRenderer.on('request-confirm', (_event, data) => callback(data)),
  sendConfirmResult: (id, result) => ipcRenderer.send('confirm-result', { id, result }),
  // App info
  getVersion: () => ipcRenderer.invoke('get-app-version'),
  getName: () => ipcRenderer.invoke('get-app-name')
});
